language: node_js
node_js:
- 8.12.0
before_script: |
  export NODE_OPTIONS=--max_old_space_size=4096

env:
  global:
    - secure: ""

jobs:
 include:
    - stage: Test
      script:
        - npm run test
    
    - stage: Deploy website to amazon s3
      script:
        - CI=false npm run build
      deploy:
        provider: s3
        access_key_id: $AWS_ACCESS_KEY_ID
        secret_access_key: $AWS_SECRET_ACCESS_KEY
        bucket: drugmlvis.gehlenborglab.org
        local_dir: build
        skip_cleanup: true
        region: us-east-2
        acl: public_read
        on:
          branch: master